### ISSUE TITLE
Unable to install packages on windows using pip

### ISSUE THREAD

**Issue by njayaram75858** [colesbury/nogil#127]
Whenever I try to install a package using pip on windows, I get an error related to shutil. Please find the logs below:

(myenv2) C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Scripts>pip install kiteconnect
Collecting kiteconnect
  Using cached kiteconnect-4.2.0-py3-none-any.whl (24 kB)
Collecting service-identity>=18.1.0 (from kiteconnect)
  Obtaining dependency information for service-identity>=18.1.0 from https://files.pythonhosted.org/packages/0c/42/bf07f277b45da6e350df3314804aa2b5411e0938d3b78b4f17da2e1302c2/service_identity-23.1.0-py3-none-any.whl.metadata
  Using cached service_identity-23.1.0-py3-none-any.whl.metadata (5.5 kB)
Collecting requests>=2.18.4 (from kiteconnect)
  Obtaining dependency information for requests>=2.18.4 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting six>=1.11.0 (from kiteconnect)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyOpenSSL>=17.5.0 (from kiteconnect)
  Obtaining dependency information for pyOpenSSL>=17.5.0 from https://files.pythonhosted.org/packages/f0/e2/f8b4f1c67933a4907e52228241f4bd52169f3196b70af04403b29c63238a/pyOpenSSL-23.2.0-py3-none-any.whl.metadata
  Using cached pyOpenSSL-23.2.0-py3-none-any.whl.metadata (10 kB)
Collecting python-dateutil>=2.6.1 (from kiteconnect)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting autobahn[twisted]==19.11.2 (from kiteconnect)
  Using cached autobahn-19.11.2-py2.py3-none-any.whl (771 kB)
INFO: pip is looking at multiple versions of kiteconnect to determine which version is compatible with other requirements. This could take a while.
Collecting kiteconnect
  Using cached kiteconnect-4.1.0-py3-none-any.whl (24 kB)
Collecting enum34>=1.1.6 (from kiteconnect)
  Using cached enum34-1.1.10-py3-none-any.whl (11 kB)
Collecting kiteconnect
  Using cached kiteconnect-4.0.2-py3-none-any.whl (24 kB)
  Using cached kiteconnect-4.0.0-py3-none-any.whl (24 kB)
  Using cached kiteconnect-3.9.6.tar.gz (24 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      Collecting setuptools>=40.8.0
        Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Installing collected packages: wheel, setuptools
      Successfully installed setuptools-68.2.2 wheel-0.41.2
      Traceback (most recent call last):
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\__pip-runner__.py", line 50, in <module>
          runpy.run_module("pip", run_name="__main__", alter_sys=True)
        File "<frozen runpy>", line 226, in run_module
        File "<frozen runpy>", line 98, in _run_module_code
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\__main__.py", line 24, in <module>
          sys.exit(_main())
                   ^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\cli\main.py", line 79, in main
          return command.main(cmd_args)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\cli\base_command.py", line 100, in main
          with self.main_context():
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\contextlib.py", line 144, in __exit__
          next(self.gen)
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\cli\command_context.py", line 19, in main_context
          with self._main_context:
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\contextlib.py", line 589, in __exit__
          raise exc_details[1]
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\contextlib.py", line 574, in __exit__
          if cb(*exc_details):
             ^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\contextlib.py", line 144, in __exit__
          next(self.gen)
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 31, in global_tempdir_manager
          with ExitStack() as stack:
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\contextlib.py", line 589, in __exit__
          raise exc_details[1]
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\contextlib.py", line 574, in __exit__
          if cb(*exc_details):
             ^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 156, in __exit__
          self.cleanup()
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
          rmtree(self._path)
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
          return self(f, *args, **kw)
                 ^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
          do = self.iter(retry_state=retry_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
          raise retry_exc.reraise()
                ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
          raise self.last_attempt.result()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\concurrent\futures\_base.py", line 449, in result
          return self.__get_result()
                 ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\Lib\concurrent\futures\_base.py", line 401, in __get_result
          raise self._exception
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
          result = fn(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nagarjuna\nogil_python\nogil-3.12\myenv2\Lib\site-packages\pip\_internal\utils\misc.py", line 128, in rmtree
          shutil.rmtree(dir, ignore_errors=ignore_errors, onexc=rmtree_errorhandler)
      TypeError: rmtree() got an unexpected keyword argument 'onexc'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by njayaram75858** [comment]
Issue seems to be related to 3.12 and it disappeared after moving to 3.10 branch

**Comment by agret** [comment]
I have been getting this error a lot when I try to install packages, how do you switch your Python to 3.10?
My current python is Python 3.12.0a4

Edit: I upgraded to Python 3.12.1 and it fixed this particular script, hopefully it doesn't break some other stuff I was using.
