### ISSUE TITLE
networkx 2.6: TypeError by passing None as closure to types.FunctionType()

### ISSUE THREAD

**Issue by fumitoh** [colesbury/nogil#38]
Hi, I tried to import `networkx`  and encountered an error:

```
>>> import networkx as nx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fumito/nogil/nogil_build/lib/python3.9/site-packages/networkx/__init__.py", line 79, in <module>
    from networkx import algorithms
  File "/home/fumito/nogil/nogil_build/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 74, in <module>
    from networkx.algorithms import isomorphism
  File "/home/fumito/nogil/nogil_build/lib/python3.9/site-packages/networkx/algorithms/isomorphism/__init__.py", line 3, in <module>
    from networkx.algorithms.isomorphism.matchhelpers import *
  File "/home/fumito/nogil/nogil_build/lib/python3.9/site-packages/networkx/algorithms/isomorphism/matchhelpers.py", line 194, in <module>
    numerical_edge_match = copyfunc(numerical_node_match, "numerical_edge_match")
  File "/home/fumito/nogil/nogil_build/lib/python3.9/site-packages/networkx/algorithms/isomorphism/matchhelpers.py", line 22, in copyfunc
    return types.FunctionType(
TypeError: arg 5 (closure) must be tuple
```
[`numerical_node_match.__closure__`](https://github.com/networkx/networkx/blob/networkx-2.7/networkx/algorithms/isomorphism/matchhelpers.py#L161-L180) is `None`,  so `None` is passed to [`copyfunc`](https://github.com/networkx/networkx/blob/networkx-2.7/networkx/algorithms/isomorphism/matchhelpers.py#L21-L25) instead of a  tuple.  The original CPython doesn't rasie the error.

**Comment by colesbury** [comment]
Thanks for the bug report @fumitoh. `networkx` 2.6+ expose some issues with the nogil interpreter that aren't easy to resolve. In particular, there are some complicated cases involving modifying `__kwdefaults__` and `__code__` attributes on functions. I'll need to think a bit on how to handle those issues.

In the meantime, I think `networkx` 2.5.1 is compatible with nogil Python.
