### ISSUE TITLE
pytest InternalError when exception in pyx numpy code

### ISSUE THREAD

**Issue by lesteve** [colesbury/nogil#57]
To reproduce:

```py
# /tmp/test.py

import numpy as np

def test_format_exc_with_compiled_code():
    np.random.uniform('invalid_value')
```

```nogil ❯ pytest /tmp/test.py   
==================================================================== test session starts ====================================================================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tmp
collected 1 item                                                                                                                                            

../../tmp/test.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/runner.py", line 126, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/runner.py", line 217, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/skipping.py", line 272, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/runner.py", line 337, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/reports.py", line 322, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/python.py", line 1677, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/nodes.py", line 398, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 648, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 905, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 846, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 797, in repr_traceback_entry
INTERNALERROR>     reprargs = self.repr_args(entry) if not short else None
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 706, in repr_args
INTERNALERROR>     for argname, argvalue in entry.frame.getargs(var=True):
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 177, in getargs
INTERNALERROR>     for arg in self.code.getargs(var):
INTERNALERROR>   File "/home/lesteve/venvs/nogil/lib/python3.9/site-packages/_pytest/_code/code.py", line 120, in getargs
INTERNALERROR>     return raw.co_varnames[:argcount]
INTERNALERROR> TypeError: 'NoneType' object is not subscriptable

=================================================================== no tests ran in 0.13s ===================================================================
```

**Comment by colesbury** [comment]
Thanks, I'm able to reproduce the issue and will keep looking into it.

**Comment by colesbury** [comment]
This is fixed now in https://github.com/colesbury/nogil/commit/0126b8947b38d6caece644c43e2d96e46bc53252. The docker images aren't rebuilt yet -- I'll do that later this week.
