### ISSUE TITLE
unable to install tensorflow with nogil

### ISSUE THREAD

**Issue by zigzagcai** [colesbury/nogil#70]
It seems that nogil has compatability with tensorflow package. I have a python script that has tensorflow as its dependency, but when I try to run it with nogil, it reports error. Do you have any ideas about how to fix this compatability. Thanks!

ErrorMsg:
python3 -m pip install tensorflow
Looking in indexes: https://d1yxz45j0ypngg.cloudfront.net/, https://pypi.org/simple
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Comment by colesbury** [comment]
Hi @zigzagcai, I haven't published a compatible tensorflow package yet because I wasn't sure how to build a tensorflow wheel and no one had asked for it yet. I'll look into this again, but it'll probably be a few weeks before I get to it.

**Comment by zigzagcai** [comment]
Thanks! @colesbury

**Comment by zigzagcai** [comment]
Updated:

I have tried building tensorflow 2.6.0 and 2.2.0 from source using bazel ([following TF official guide](https://www.tensorflow.org/install/source)). It reports errors about `keras_python_api_gen failed`. However when I build tensorflow with original python3.9, no error accured.

Do we need to modify TF codes when using nogil? Thanks very much if anybody can provide some insights about how to build nogil compatible TensorFlow wheels.

TensorFlow Build Log:
```
bazel build --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=126
INFO: Reading rc options for 'build' from /root/zheng/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /root/zheng/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /root/zheng/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/root/.pyenv/versions/nogil-3.9.10/bin/python3 --action_env PYTHON_LIB_PATH=/root/.pyenv/versions/nogil-3.9.10/lib/python3.9/site-packages --python_path=/root/.pyenv/versions/nogil-3.9.10/bin/python3
INFO: Found applicable config definition build:short_logs in file /root/zheng/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/zheng/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file /root/zheng/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:v2 in file /root/zheng/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /root/zheng/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /root/zheng/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/zheng/tensorflow/tensorflow/python/keras/api/BUILD:120:19: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/core/framework/tensor_shape_pb2.py", line 35, in <module>
    fields=[
  File "/root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/com_google_protobuf/python/google/protobuf/descriptor.py", line 530, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/zheng/tensorflow/tensorflow/tools/pip_package/BUILD:69:10 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
INFO: Elapsed time: 1.240s, Critical Path: 0.60s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
```


package list of nogil python:
```
Package             Version
------------------- ---------
certifi             2022.6.15
charset-normalizer  2.1.0
Cython              0.29.26
idna                3.3
jsonpickle          2.2.0
keras               2.9.0
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.2
mock                4.0.3
numpy               1.22.3
opt-einsum          3.3.0
packaging           21.3
pip                 21.3.1
protobuf            3.8.0
pyparsing           3.0.9
requests            2.28.1
setuptools          58.1.0
six                 1.16.0
urllib3             1.26.10
wheel               0.37.1
```

**Comment by zigzagcai** [comment]
Updated:
I have successfully built tensorflow v2.6.0 wheels for nogil. Now it is fully compatible with nogil-python.

The cause of TF Build Error is `protobuf` version. After reinstall protobuf with specific version(`pip install protobuf~=3.19.0`), the issues was solved.

Here is the successful TensorFlow build log:
```
bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=126
INFO: Reading rc options for 'build' from /root/zheng/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /root/zheng/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /root/zheng/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/root/.pyenv/versions/nogil-3.9.10/bin/python3 --action_env PYTHON_LIB_PATH=/root/.pyenv/versions/nogil-3.9.10/lib/python3.9/site-packages --python_path=/root/.pyenv/versions/nogil-3.9.10/bin/python3
INFO: Found applicable config definition build:short_logs in file /root/zheng/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /root/zheng/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /root/zheng/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /root/zheng/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /root/.cache/bazel/_bazel_root/48b5d35dda8f11d41e830988f33019fa/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (429 packages loaded, 26703 targets configured).
INFO: Found 1 target...
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 778.868s, Critical Path: 440.48s
INFO: 9981 processes: 1011 internal, 8970 local.
INFO: Build completed successfully, 9981 total actions
```

package list of nogil python:
```
Package             Version
------------------- ---------
certifi             2022.6.15
charset-normalizer  2.1.0
Cython              0.29.26
idna                3.3
jsonpickle          2.2.0
keras               2.9.0
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.2
mock                4.0.3
numpy               1.22.3
opt-einsum          3.3.0
packaging           21.3
pip                 21.3.1
protobuf            3.19.4
pyparsing           3.0.9
requests            2.28.1
setuptools          58.1.0
six                 1.16.0
urllib3             1.26.10
wheel               0.37.1
```

**Comment by zigzagcai** [comment]
Is there a way to upload tensorflow wheels into nogil [alternative package index](https://d1yxz45j0ypngg.cloudfront.net/)? So that other people can use TF with nogil.
Thanks!

**Comment by zigzagcai** [comment]
This issue has been resolved.

**Comment by colesbury** [comment]
Hi @zigzagcai, you might run into issues because of pybind11. Pybind11 requires patches to be thread-safe without the GIL. If you "pip install pybind11", you'll get the patched version, but I think TensorFlow embeds it somehow with bazel.

**Comment by colesbury** [comment]
I've uploaded a version of TensorFlow 2.6.5 with the patched pybind11. You should get it with `pip install tensorflow`.

Changes are here:
https://github.com/colesbury/tensorflow/tree/v2.6.5-nogil
