### ISSUE TITLE
nogil runtime error

### ISSUE THREAD

**Issue by houshijie-2020** [colesbury/nogil#83]
printf Py_GetPythonHome : /usr/local/nogil-py/

printf Py_GetPythonPath : /usr/local/nogil-py/lib/python39.zip:/usr/local/nogil-py/lib:/usr/local/nogil-py/lib/python3.9/site-packages:/usr/local/nogil-py/lib/python3.9:/usr/local/nogil-py/lib/python3.9/lib-dynload:/usr/local/nogil-py/lib/python39.zip:/usr/local/nogil-py/lib/python3.9:/usr/local/nogil-py/lib/python3.9/lib-dynload
 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/nogil-py/lib/python3.9/site-packages/MNN/__init__.py", line 4, in <module>
    from _mnncengine import *
ImportError: /usr/local/nogil-py/lib/python3.9/site-packages/_mnncengine.nogil-39b-x86_64-linux-gnu.so: undefined symbol: _Py_TrueStruct

**Comment by houshijie-2020** [comment]
#include <iostream>
#include <stdio.h>
#include <string>

#include "Python.h"

using namespace std;

void Python_run_str(const string& str)
{
    PyRun_SimpleString(str.c_str());

}

void Python_run_file(const string& file_name)
{
    FILE* file;
    file = fopen(file_name.c_str(), "r");
    PyRun_SimpleFile(file, file_name.c_str());
    fclose(file);
}

int main()
{
    printf("printf Py_GetPythonHome : %ls\n\n\n\n", Py_GetPythonHome());

    Py_Initialize();
    printf("printf content start: %ls\n\n\n\n", Py_GetPath());
    Python_run_str("import  MNN\nprint('import  MNN sucessfully')\n");

    if (Py_FinalizeEx() < 0) {
        cout << "Py_FinalizeEx err" << endl;
        exit(120);
    }

    int a = 0;
    cout << "input a integer" << endl;
    cin >> a;
    return 0;
}

**Comment by colesbury** [comment]
It's not clear to me what's you're trying to do. It looks like you have a custom C API extension and also are trying to embed the interpreter? It looks likely that you have some build misconfiguration.

Can you put together a complete reproduction, including the code and commands to build it?

**Comment by houshijie-2020** [comment]
i am  trying to embed the interpreter （MNN is a a custom C API extension）
**the comiple command:**
gcc test_mnn.cpp  -lstdc++ -I/usr/local/nogil-py/include/python3.9/ -lm -L/usr/local/nogil-py/lib/ -lpython3.9 -lpthread  -lutil -ldl -o test_mnn

**gcc version:**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure -enable-checking=release -enable-languages=c,c++ -disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.3.0 (GCC) 


**export:** 
export PYTHONPATH=/usr/local/nogil-py/lib/python39.zip:/usr/local/nogil-py/lib:/usr/local/nogil-py/lib/python3.9/site-packages:/usr/local/nogil-py/lib/python3.9:/usr/local/nogil-py/lib/python3.9/lib-dynload
 
export PYTHONHOME=/usr/local/nogil-py/
